_LVOLockRealTime            	EQU	-30
_LVOUnlockRealTime          	EQU	-36
_LVOCreatePlayerA           	EQU	-42
_LVODeletePlayer            	EQU	-48
_LVOSetPlayerAttrsA         	EQU	-54
_LVOSetConductorState       	EQU	-60
_LVOExternalSync            	EQU	-66
_LVONextConductor           	EQU	-72
_LVOFindConductor           	EQU	-78
_LVOGetPlayerAttrsA         	EQU	-84
